### ISSUE TITLE
Cors Enabled: Options Method Not Allowed

### ISSUE THREAD

**Issue by JouperCoding** [micronaut-projects/micronaut-aws#1214]
### Expected Behavior

OPTIONS Method or CORS preflight request should respond with 200 if the given request headers

Access-Control-Request-Method: POST
Access-Control-Request-Headers: authorization,content-type,x-api-version

is allowed per the CORS configuration details.

```
    cors:
      enabled: true
      single-header: true
      configurations:
        web:
          maxAge: 3600
          allowedOrigins:
            - someOrigin
            - ^http(|s):\/\/(|www\.)(.*?)(|:[0-9]+)$
          allowedMethods:
            - HEAD
            - OPTIONS
            - POST
            - GET
          allowedHeaders:
            - Content-Type
            - Authorization
            - X-Api-Version
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
```

Note the above sample of explicitly setting the allowedHeaders when running a lambda function + API GW.
The following headers are required to be allowed for it to work, but the same behavior can be achieved even if you allow *
```
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
```

### Actual Behaviour

After upgrading from Micronaut 2.5 -> 3.1.3 we started to notice alot of the following logs.

```
[ 2021-11-12 16:56:07.644 UTC +0000 ] [ WARN ] [ main ] [ myapp.api.core.exceptions.GlobalValidationResponseHandler.processResponse 37 ] - [OPTIONS] - /myapi/login
Access-Control-Request-Method: POST
Access-Control-Request-Headers: authorization,content-type,x-api-version
```

We have enabled cors as following, by explicitly adding the Amazon API GW headers + the default allowed headers. (Note same issue occurs even with allowing all headers *.

```
    cors:
      enabled: true
      single-header: true
      configurations:
        web:
          maxAge: 3600
          allowedOrigins:
            - someOrigin
            - ^http(|s):\/\/(|www\.)(.*?)(|:[0-9]+)$
          allowedMethods:
            - HEAD
            - OPTIONS
            - POST
            - GET
          allowedHeaders:
            - Content-Type
            - Authorization
            - X-Api-Version
            - X-Site-Name
            - X-Site-Secret
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
```

Even when adding @Options to our controllers for each endpoint we have, for example like this.

```
	@Options("/login")
	public HttpResponse<?> loginOptions(HttpRequest<?> request,  HttpHeaders httpHeaders){
		Optional<String> originOptional = httpHeaders.getOrigin();
		if(originOptional.isPresent())
			return HttpResponse.ok();
		return HttpResponse.badRequest();
	}
```

It will return a 200 success locally using netty, but when running in a lambda context using MicronautLambdaContainerHandler the following issue occurs when trying to get and optional value without checking if the value is present.

```
[ io.micronaut.http.server.RouteExecutor.logException 421 ] - Unexpected error occurred: No value present java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:148)
    at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.lambda$handleRouteMatch$3(MicronautLambdaContainerHandler.java:344)
```
see: https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java#L344

However, i'm not sure how Micronaut handles Options calls / Preflight CORS calls and how that integrates with Amazon API Gateway. If I remember correctly all lambda invocations happens via POST from API GW.

### Steps To Reproduce

See sample project https://github.com/JouperCoding/jc-micronaut-cors

### Example Application

https://github.com/JouperCoding/jc-micronaut-cors

### Version

3.1.3
