### ISSUE TITLE
API Gateway Proxy Integration payload format 2.0 incompatible

### ISSUE THREAD

**Issue by forresthopkinsa** [micronaut-projects/micronaut-aws#1317]
### Expected Behavior

API Gateway HTTP API using proxy integration with a Lambda running Micronaut should work by default

### Actual Behaviour

Micronaut silently fails to parse parameters from the default Proxy Integration payload format (2.0) and so every request is read as a `GET /` (and it is very, _very_ difficult to troubleshoot)

### Steps To Reproduce

1. Create a `Micronaut Application` from Micronaut Launch using all defaults, with the 'aws-lambda' feature
1. Deploy jar to a Corretto 11 Lambda
1. Set Lambda handler to `io.micronaut.function.aws.proxy.MicronautLambdaHandler`
1. Create an HTTP API in APIGW
1. Hook up an `ANY /{proxy+}` route to the Micronaut lambda
1. Try to POST the APIGW default endpoint with a valid body for `BookController.save`
1. Server responds:

```json
{
  "message": "Method Not Allowed",
  "_links": {
    "self": {
      "href": "https://myapigw.execute-api.us-east-2.amazonaws.comnull",
      "templated": false
    }
  },
  "_embedded": {
    "errors": [
      {
        "message": "Method [GET] not allowed for URI [https://myapigw.execute-api.us-east-2.amazonaws.comnull]. Allowed methods: [POST]"
      }
    ]
  }
}
```

### Environment Information

micronaut-cli.yml

```yml
applicationType: default
defaultPackage: com.example
testFramework: junit
sourceLanguage: java
buildTool: gradle
features: [annotation-api, app-name, aws-lambda, gradle, jackson-databind, java, java-application, junit, logback, micronaut-build, readme, shade, yaml]
```

### Version

3.4.0
