### ISSUE TITLE
Swagger Static Resource does not work with Micronaut Lamdba Applications

### ISSUE THREAD

**Issue by vyusuf** [micronaut-projects/micronaut-aws#1361]
### Expected Behavior

When setting static routes in application.yml, I expect the routes to serve the files in the paths defined
i.e.
```
micronaut:
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**
```

### Actual Behaviour

Returns a `Page not Found` response

### Steps To Reproduce

1. Create a new kotlin/gradle application using [micronaut launch](https://micronaut.io/launch) selecting the following features: aws-lambda, openapi, swagger-ui
2. ./gradlew run
3. Try hitting the endpoint: `http://localhost:8080/swagger-ui/`
4. You get `Page Not Found` and I believe [this](https://github.com/micronaut-projects/micronaut-aws/pull/1194/files/224f4251e7e7a8e09cb71264eaf8917547be42a6#r865885130) is were the regression was introduced because it not longer checks for static resources like it used to

### Environment Information

- MacOS
- Windows

### Version

3.4.3
