### ISSUE TITLE
Changing jackson config causes weird behavior of Lambda request handling

### ISSUE THREAD

**Issue by RoadRunner120485** [micronaut-projects/micronaut-aws#186]
I found a problem with the whole Lambda handling, when changing the configuration of the default `ObjectMapper` in Micronaut:
```
jackson:
  bean-introspection-module: true
  propertyNamingStrategy: SNAKE_CASE
  serializationInclusion: NON_ABSENT
  dateFormat: yyyy-MM-dd'T'HH:mm:ss:SSSZ
  timeZone: CET
```

This is because the `MicronautLambdaContainerHandler` uses the global `ObjectMapper`. I would expect, that the framework would use a seperate one, which is configured to just met the Lambda specifications or at least that the properties of classes used for Lambda API (like `AwsProxyRequest`) are annotated with `@JsonProperty` etc.

Im using Micronaut `1.2.9`
