### ISSUE TITLE
[Doc] Distributed configuration with SecretsManager

### ISSUE THREAD

**Issue by chjourdain** [micronaut-projects/micronaut-aws#1920]
### Issue description

Hello,

While using micronaut 3, with a distributed configuration on secretManager I declared the following `bootstrap.yml`

```
micronaut:
  config-client:
    enabled: true
  application:
    name: someApplication
aws:
  secretsmanager:
    secrets:
      - secret-name: rds

```

Moving to micronaut 4, I had to add a 'client' wrapper, or it refused to work

```
micronaut:
  config-client:
    enabled: true
  application:
    name: someApplication
aws:
  client:
    secretsmanager:
      secrets:
        - secret-name: rds

```

The [documentation for secretManager](https://micronaut-projects.github.io/micronaut-aws/latest/guide/#distributedconfigurationsecretsmanager)  does not mention it whereas every other item do [ParameterStore_documentation](https://docs.micronaut.io/4.0.2/guide/index.html#distributedConfigurationAwsParameterStore)

## Version

Latest with AWS 4.0.3
