### ISSUE TITLE
Controller Version Routing - sam local start-api

### ISSUE THREAD

**Issue by JouperCoding** [micronaut-projects/micronaut-aws#389]
When creating a @Controller which defines endpoints with the @Version annotation, the requests using X-API-VERSION header is not routed to the right method in a sam local start-api context. Running the same code using netty to serve the API locally works as intended

### Steps to Reproduce

1. Create a new function app
2. Create handler using RequestHandler and a Micronaut Lambda Container
3. Create a @Controller with two APIs using two versions

### Expected Behaviour

Sending X-API-VERSION header should route to the right method using @Version annotation

### Actual Behaviour

Always routes to first matched method.

### Environment Information

- **Operating System**: WIN 10
- **Micronaut Version:** 2.0
- **JDK Version:** Amazon Coretto 8

### Example Code

	@Get("/ping")
	public String pingV1() {
		log.info("Received a ping.");
		return "pong";
	}

	@Version("2")
	@Get("/ping")
	public String pingV2() {
		log.info("Received a ping.");
		return "pong v2";
	}

**Comment by ilopmar** [comment]
@JouperCoding can you please provide an sample `sam.yaml` file and the `sam` command you use to start the app?

**Comment by JouperCoding** [comment]
Looks like you were able to resolve this before I had a chance to respond :)

Quick question, when can I expect this fix to be release in 2.0.0?

Thanks!

**Comment by ilopmar** [comment]
@JouperCoding Well, I wasn't able to test it on sam-local, only on tests, so it would be great if you can provide the yaml template.

We need to discuss a few things about this issue before releasing micronaut-aws 2.0.1 but in the meantime you can try the 2.0.1.BUILD-SNAPSHOT version.

**Comment by JouperCoding** [comment]
@ilopmar Im using the following saml yaml template. and im running 

gradlew.bat build && sam local start-api -t public-api.yaml


```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Private API (Client <-> Server)
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  PublicApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.handlers.PublicApiHandler
      Runtime: java8
      CodeUri: build/exploded
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Tracing: Active
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  PublicApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: PublicApi
```

I will try the 2.0.1.BUILD-SNAPSHOT today! thanks
