### ISSUE TITLE
MicronautLambdaContainerHandler does not proxy static routes

### ISSUE THREAD

**Issue by kastork** [micronaut-projects/micronaut-aws#67]
If you set up your fatJar with some static resources and configure the app like so....

```yaml
micronaut:
  security:
    enabled: true
    intercept-url-map:
      -
        pattern: /**
        http-method: GET
        access:
          - isAnonymous()
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

```

Requests like `GET /statics/icon/favicon.ico` are not proxied.  Therefore gateway just returns a 404. 

This makes it hard to deliver something like an SPA out of your jar.
